---
title: "Preliminary Vis of Workshop Attendees"
author: "John Little"
date: "`r Sys.Date()`"
output:
  html_notebook: default
---

First run `rmarkdown::render("01_make-attendance-roster.Rmd")`

```{r include=FALSE}
library(tidyverse)
```

## Wrangle

Transform Discipline Names

```{r include=FALSE}
roster2 <- Roster %>% 
  rename(status = `Academic Status (or other)`) %>% 
  rename(patron = `Have you consulted with Data and Visualization Services before this workshop?`) %>% 
  rename(advertizing_source = 'Where did you hear about this event?') %>% 
  rename(affiliate = "Are you affiliated with Duke University, Duke Medical Center, DCRI, or another Duke group?") %>% 
  rename(interest = "I'm interested in registering for this workshop because:") %>% 
  rename(discipline = `Discipline or Affiliation`) %>% 
  filter(status != "Perpetual") %>% 
  mutate(discipline = case_when(
    discipline == "African and African American Studies" ~ "Afr",
    discipline == "Art, Art History, and Visual Studies" ~ "Art",
    discipline == "Asian and Middle Eastern Studies" ~ "Asia",
    discipline == "Biology" ~ "Bio",
    discipline == "Center for Documentary Studies" ~ "Document",
    discipline == "Chemistry" ~ "Chem",
    discipline == "Classical Studies" ~ "Classics",
    discipline == "Computer Science" ~ "CS",
    discipline == "Cultural Anthropology" ~ "Anthro",
    discipline == "Dance" ~ "Dance",
    discipline == "Divinity School" ~ "Div",
    discipline == "Duke University Health System (DUHS)" ~ "DUHS",
    discipline == "Economics" ~ "Econ",
    discipline == "Education (Program in Education)" ~ "Edu",
    discipline == "Engineering (Pratt School of Engineering)" ~ "Engr",
    discipline == "English" ~ "Engl",
    discipline == "Evolutionary Anthropology" ~ "Evol-Antro",
    discipline == "Fuqua School of Business" ~ "Fuqua",
    discipline == "Gender, Sexuality, and Feminist Studies" ~ "Gender",
    discipline == "Germanic Languages and Literature" ~ "German",
    discipline == "Graduate Liberal Studies" ~ "Liberal",
    discipline == "History" ~ "Hist",
    discipline == "International Comparative Studies" ~ "Comparative Lit",
    discipline == "Law School" ~ "Law",
    discipline == "Masters in Interdisciplinary Data Science" ~ "DS",
    discipline == "Mathematics" ~ "Math",
    discipline == "Nicholas School of the Environment" ~ "Nicholas",
    discipline == "Neuroscience" ~ "Neuroscience",
    discipline == "Philosophy" ~ "Phil",
    discipline == "Political Science" ~ "Poli Sci",
    discipline == "Population Health Sciences"~ "Health Sci",
    discipline == "Psychology and Neuroscience" ~ "Psych/Neuro",
    discipline == "Religious Studies" ~ "Relgion",
    discipline == "Romance Studies" ~ "Romance",
    discipline == "Sanford School of Public Policy" ~ "Sanford",
    discipline == "Slavic and Eurasian Studies" ~ "Slavic",
    discipline == "School of Medicine" ~ "Medicine",
    discipline == "School of Nursing" ~ "Nursing",
    discipline == "Sociology" ~ "Sociology",
    discipline == "Statistical Science" ~ "Stats",
    discipline == "Theatre Studies" ~ "Theater",
    discipline == "Other / None" ~ "Other")) %>% 
  mutate(status = fct_infreq(status, ordered = TRUE) ) %>% 
  mutate(discipline = fct_infreq(discipline, ordered = TRUE))
```


```{r  include=FALSE}
roster2
```



```{r include=FALSE}
interest_inventory <- roster2 %>% 
  mutate(id = paste(`Last Name`, `First Name`, sep = "_")) %>% 
  select(id, status, discipline, interest) %>% 
  separate_rows(interest, sep = ",") %>% 
  mutate(interest = trimws(interest)) %>% 
  mutate(interest = na_if(interest, "-")) %>% 
  drop_na(interest) %>% 
  mutate(interest = case_when(
    interest == "I believe this topic is important for my career goals" ~ "Career",
    interest == "This topic is directly relevant to a course or project I'm pursuing" ~ "Course/Project",
    interest == "I am generally curious about the topic" ~ "Curious"
  )) %>% 
  mutate(interest = fct_infreq(interest, ordered = TRUE))

interest_inventory
```

## Vis


```{r echo=FALSE}
ggplot(roster2) +
  geom_bar(aes(x = fct_rev(status), fill = patron)) +
  coord_flip() +
  labs(y = "",
       x = "Status",
       title = "DVS Patron Status",
       fill = "Patron")
```

```{r echo=FALSE}
roster2 %>% 
  mutate(discipline = fct_lump(discipline, n = 9)) %>% 
  ggplot() +
  geom_bar(aes(x = fct_rev(discipline), fill = fct_rev(status))) +
  coord_flip() +
  theme(axis.text.y = element_text(angle = 45),
        axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  guides(fill=guide_legend(title="Status")) +
  labs(title = "Attendance by Discipline")
  
```


```{r echo=FALSE}
interest_inventory %>% 
  ggplot() +
  geom_bar(aes(x = fct_rev(interest), 
               fill = fct_rev(status))) +
  coord_flip() +
  labs(y = "",
       x = "Interest",
       title = "DVS Patron Interest Questionnaire",
       fill = "Status")
```


```{r echo=FALSE}
interest_inventory %>% 
  ggplot() +
  geom_bar(aes(fct_rev(fct_lump(fct_infreq(discipline), prop = 0.03)),
               fill = interest)) +
  coord_flip() +
  labs(y = "",
       x = "Discipline",
       title = "Questionnaire by Discipline",
       fill = "Interest")
```

