---
title: "Write Attedance as Google Sheet -- Version: 2018-Spring"
output: html_notebook
---

```{r}
library(tidyverse)
library(readr)
library(lubridate)
library(stringr)
library(googlesheets)
```

```{r, child="child_010_file-system_data-dir.Rmd"}
# Identify Data directory
# Load Files
# Organize Files into a Data Frame
# Generate Metadata about the Workshop from the Attendees/Confirmed-registrants File
```


```{r, child="child_020_read-attendance-files.Rmd"}
# Read in the Attendees/Registrants file
# Read in the workshop metadata from the workshop header lines
# Wrangle the Workshop Metadata
# Read in the Waitlist file
# read in the Cancelled file

```



## Combine Attendee & Waitlist 

### Attendees as Data Frame

select order of columns

```{r attendees_dataframe}

forGoogleDrive_attendees <- Attendees %>% 
  mutate("Workshop Name" = eventMetaData_attendees$Event) %>% 
  mutate("Workshop Date" = as.character(eventDate)) %>% 
  mutate(`Attended (x or blank)` = "") %>% 
  rename(`Registration Status (Registered, Waitlist, or Walk-in)` = "Registration Status") %>% 
  rename(`Booking Made` = `Booking made`) %>% 
  mutate(Attendance = "") %>% 
  select(18, 14, 17, 16, 15, 1:4, 19, 5:19) 

# tbl_vars(forGoogleDrive_attendees)
forGoogleDrive_attendees
```

### Waitlist as data frame

select order of columns

```{r waitlist_dataframe}
if("wait_list" %in% files$type){
  forGoogleDrive_WaitList <- WaitList %>% 
    mutate("Workshop Name" = eventMetaData_attendees$Event) %>% 
    mutate("Workshop Date" = as.character(eventDate)) %>% 
    mutate(`Attended (x or blank)` = "") %>% 
    rename(`Registration Status (Registered, Waitlist, or Walk-in)` = "Registration Status") %>% 
    rename(`Booking Made` = `Booking made`) %>% 
    mutate(Attendance = "") %>%
    #select(18, 14, 17, 16, 15, 1:18) 
    select(18, 14, 17, 16, 15, 1:4, 19, 5:19)
  
  #tbl_vars(forGoogleDrive_WaitList)
  
  forGoogleDrive_WaitList
}
```

### Combine Attendees and Wait List

```{r combine_attendees_and_waitlist}
if("wait_list" %in% files$type){
  forGoogleDrive_attendees <- bind_rows(
    forGoogleDrive_attendees,
    forGoogleDrive_WaitList
  ) %>% 
    arrange(`Last Name`)
} else {
  forGoogleDrive_attendees <- forGoogleDrive_attendees %>% 
    arrange(`Last Name`)
}

```



## Write to GoogleDrive 

Write Attendance / Waitlist / Walk-in Sheet to Google Drive
```{r write-to-googlesheets}
# Name of GoogleSheet (i.e. filename in Google Drive)
filename <- paste0(forGoogleDrive_attendees$`Workshop Name`[1], 
                   "_", eventDate)

test1_ss <- gs_new(filename, ws_title = filename, 
                   input = forGoogleDrive_attendees, col_names = TRUE,
                   trim = TRUE, verbose = TRUE)
```

If there's a "cancelled" list from LibCal, write that separately to Google Drive
```{r write-cancelled-to-googlesheets}
# forGoogleDrive_Cancelled was created in the script: "process_libcal_attendance.Rmd"

if("cancelled" %in% files$type){
  test1_ss <- gs_ws_new(test1_ss, ws_title = "Cancellations", 
                        input = forGoogleDrive_Cancelled,
                        col_names = FALSE, trim = TRUE, 
                        verbose = TRUE)
}
```


## email list as .csv -- to paste into dvs-announce list

```{r build-and-write-dvsannounce-list}
Roster <- bind_rows(Attendees, 
                    if("wait_list" %in% files$type){WaitList}
)

Roster %>% 
  filter(`Would you like to receive more information about DVS events and training?` == "Yes") %>% 
  select(Email) %>% 
  arrange(Email) %>% 
  write_delim("outfile/dvs-announce_append-email.txt", col_names = FALSE)

```
